# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  coursework:
    image: coursework
    build:
      context: .
      dockerfile: CourseWork/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db: 
    image: postgres:15 
    container_name: CourseWorkDB
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Workers
    ports:
      - "5432:5432" 
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
